// Satirical demo profiles of public figures
// All data is fictional and for entertainment purposes only

const computeDaysAgo = (lastContact: string): number => {
  const date = new Date(lastContact);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  date.setHours(0, 0, 0, 0);
  return Math.floor((today.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));
};

export const generateDemoContacts = () => {
  const now = new Date().toISOString();

  return [
    {
      id: 'demo-elon',
      slug: 'elon-musk-demo',
      name: 'Elon Musk',
      initials: 'EM',
      title: 'Chief Meme Officer',
      company: 'X (formerly Twitter, formerly my dignity)',
      location: 'Mars (eventually)',
      email: 'totallyreal@x.com',
      phone: '+1 (420) 694-2069',
      tags: ['Work', 'Friend'],
      lastContact: '2026-01-10',
      nextMeetDate: '2026-02-14',
      personalNotes: 'Keeps trying to sell me a flamethrower. Says "X" is the everything app but still can\'t edit tweets properly. Promised me a Cybertruck in 2019. Still waiting. Now wants to put a chip in my brain. Hard pass.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'June 28', type: 'text' },
        { id: '2', label: 'Favorite Topic', value: 'Himself', type: 'text' },
        { id: '3', label: 'Red Flags', value: '🚩🚩🚩 Too many to count', type: 'text' },
        { id: '4', label: 'Spirit Animal', value: 'Doge (obviously)', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-1',
          title: 'Coffee at SpaceX HQ',
          body: 'Spent 2 hours explaining why Mars needs a drive-thru Starbucks. Drew rocket designs on napkin. Napkin is now worth $50M apparently.',
          date: '2025-12-15T10:00:00Z',
        },
        {
          id: 'note-2',
          title: 'Twitter Spaces Disaster',
          body: 'Hosted a Space about "free speech". Muted 47 people who disagreed. See no irony.',
          date: '2025-11-20T15:30:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-zuck',
      slug: 'mark-zuckerberg-demo',
      name: 'Mark Zuckerberg',
      initials: 'MZ',
      title: 'Metaverse Enthusiast',
      company: 'Meta (the company, not the concept)',
      location: 'The Metaverse (nobody else is there)',
      email: 'definitely.human@meta.com',
      phone: '+1 (555) VR-LEGS',
      tags: ['Work'],
      lastContact: '2025-12-01',
      nextMeetDate: '2026-03-01',
      personalNotes: 'Still insisting the metaverse is the future. Showed up to lunch wearing VR headset. Kept bumping into tables. Offered me $1B to join Horizon Worlds. Saw one person there. It was Mark on a different account.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'May 14', type: 'text' },
        { id: '2', label: 'Hobbies', value: 'Collecting your data, MMA training, BBQ', type: 'text' },
        { id: '3', label: 'Fun Fact', value: 'Blinks once every 47 seconds', type: 'text' },
        { id: '4', label: 'Weakness', value: 'Congress hearings, privacy laws', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-3',
          title: 'Meta HQ Tour',
          body: '$10B metaverse demo. My legs were floating cubes. Mark said "that\'s a feature." I left.',
          date: '2025-10-10T14:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-taylor',
      slug: 'taylor-swift-demo',
      name: 'Taylor Swift',
      initials: 'TS',
      title: 'Eras Tour Director',
      company: 'Taylor Swift LLC',
      location: 'Somewhere in North America (check Ticketmaster)',
      email: 'gorgeous@taylorswift.com',
      phone: '+1 (989) 989-1989',
      tags: ['Friend'],
      lastContact: '2026-01-13',
      personalNotes: 'Met at a party. We had a great conversation. Didn\'t hear from her for a week. Then her new album dropped. Track 5 is about me. I only said "nice sweater."',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'Dec 13', type: 'text' },
        { id: '2', label: 'Known For', value: 'Writing breakup songs faster than you can swipe right', type: 'text' },
        { id: '3', label: 'Warning', value: 'Everything you say will become a song', type: 'text' },
        { id: '4', label: 'Superpower', value: 'Crashing Ticketmaster servers', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-4',
          title: 'Brunch in NYC',
          body: 'Brought her guitar. I made a joke about cats. She started writing lyrics. I excused myself. Album drops next month.',
          date: '2025-11-30T11:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-lebron',
      slug: 'lebron-james-demo',
      name: 'LeBron James',
      initials: 'LJ',
      title: 'The Kid from Akron',
      company: 'Lakers / Space Jam Productions',
      location: 'Los Angeles',
      email: 'kingjames@goat.com',
      phone: '+1 (330) 234-5678',
      tags: ['Friend', 'Work'],
      lastContact: '2026-01-05',
      nextMeetDate: '2026-01-25',
      personalNotes: 'Asked for career advice. He said "Just be the GOAT." Thanks LeBron. Very helpful. Also won\'t stop posting Instagram stories of his workouts at 5am. We get it, you\'re in shape.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'Dec 30', type: 'text' },
        { id: '2', label: 'Signature Move', value: 'The LeBlock', type: 'text' },
        { id: '3', label: 'Daily Routine', value: '5am workout + 47 Instagram posts', type: 'text' },
        { id: '4', label: 'Taco Tuesday', value: 'A lifestyle, not just a meal', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-5',
          title: 'Pickup Game',
          body: 'Invited me to "casual" basketball. He brought a film crew and dunked on me 15 times. Posted highlight reel. I\'m now a meme.',
          date: '2025-12-20T16:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-oprah',
      slug: 'oprah-winfrey-demo',
      name: 'Oprah Winfrey',
      initials: 'OW',
      title: 'Media Mogul & Car Giver',
      company: 'OWN Network',
      location: 'Montecito',
      email: 'favorite.things@oprah.com',
      phone: '+1 (888) GET-A-CAR',
      tags: ['Work', 'Friend'],
      lastContact: '2025-12-18',
      nextMeetDate: '2026-02-12',
      personalNotes: 'Had lunch. She gave the waiter a car. Then the chef. Then me. I already have a car. She said "now you have TWO cars!" Can\'t argue with that logic. Added to book club without consent.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'Jan 29', type: 'text' },
        { id: '2', label: 'Famous Quote', value: 'You get a car! And YOU get a car!', type: 'text' },
        { id: '3', label: 'Book Club', value: 'Mandatory attendance', type: 'text' },
        { id: '4', label: 'Power Level', value: 'Over 9000', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-6',
          title: 'Book Club Meeting',
          body: 'Chose a 900-page autobiography of someone I\'ve never heard of. Everyone pretended to read it. Oprah knew. She knows everything.',
          date: '2025-11-15T18:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-gordon',
      slug: 'gordon-ramsay-demo',
      name: 'Gordon Ramsay',
      initials: 'GR',
      title: 'Hell\'s Kitchen Survivor',
      company: 'Gordon Ramsay Restaurants',
      location: 'London',
      email: 'itsraw@hk.com',
      phone: '+44 (20) F-WORD',
      tags: ['Acquaintance'],
      lastContact: '2026-01-09',
      personalNotes: 'Made him dinner. He called it "an insult to food." Then ate three plates. Asked for the recipe. Refuses to admit it was good. Classic Gordon.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'Nov 8', type: 'text' },
        { id: '2', label: 'Catch Phrase', value: 'IT\'S RAW!', type: 'text' },
        { id: '3', label: 'Secret', value: 'Actually very nice (don\'t tell anyone)', type: 'text' },
        { id: '4', label: 'Weakness', value: 'Frozen food, bad plating, me', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-7',
          title: 'Dinner Critique',
          body: 'Cooked pasta. He said "my nan could do better, and she\'s dead." Then asked for seconds. Confusing experience.',
          date: '2025-12-05T19:30:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-beyonce',
      slug: 'beyonce-demo',
      name: 'Beyoncé',
      initials: 'B',
      title: 'Queen Bey',
      company: 'Parkwood Entertainment',
      location: 'Everywhere and nowhere',
      email: 'irreplaceable@beyonce.com',
      phone: '+1 (713) DESTINY',
      tags: ['Friend'],
      lastContact: '2026-01-11',
      nextMeetDate: '2026-02-05',
      personalNotes: 'We\'re friends but I\'ve never actually met her. She just IS there. Materialized at my birthday party. Nobody knows how. Sang "Happy Birthday" in perfect harmony with herself. Pretty sure she\'s a goddess.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'Sep 4', type: 'text' },
        { id: '2', label: 'Status', value: 'Actual royalty', type: 'text' },
        { id: '3', label: 'Powers', value: 'Omnipresence, perfect vocals, wind machine control', type: 'text' },
        { id: '4', label: 'Weakness', value: 'None detected', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-8',
          title: 'Mysterious Appearance',
          body: 'Was thinking about Beyoncé. She appeared. Sang "Halo." Left without explanation. Did this happen?',
          date: '2025-10-30T20:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-bezos',
      slug: 'jeff-bezos-demo',
      name: 'Jeff Bezos',
      initials: 'JB',
      title: 'Former CEO, Current Space Cowboy',
      company: 'Blue Origin',
      location: 'Space (trying really hard)',
      email: 'prime@amazon.com',
      phone: '+1 (206) 266-2958',
      tags: ['Work'],
      lastContact: '2025-11-29',
      nextMeetDate: '2026-01-10',
      personalNotes: 'Asked why Amazon packages arrive late. He launched himself into space mid-conversation. Came back 11 minutes later. Still didn\'t answer the question.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'Jan 12', type: 'text' },
        { id: '2', label: 'Hobbies', value: 'Space, buying boats, union busting', type: 'text' },
        { id: '3', label: 'Laugh', value: 'Villainous (seriously, Google it)', type: 'text' },
        { id: '4', label: 'Goal', value: 'Beat Elon to Mars, eliminate bathroom breaks', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-9',
          title: 'Blue Origin Test Flight',
          body: 'Invited to space. Declined. Too many mixed reviews on Amazon.',
          date: '2025-09-12T09:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-dwayne',
      slug: 'the-rock-demo',
      name: 'Dwayne "The Rock" Johnson',
      initials: 'TR',
      title: 'People\'s Champion',
      company: 'Seven Bucks Productions',
      location: 'The Gym (always)',
      email: 'canyousmell@therock.com',
      phone: '+1 (305) LAYDOWN',
      tags: ['Friend'],
      lastContact: '2026-01-02',
      personalNotes: 'Nicest guy ever. Made me breakfast. It was 47 eggs and a cow. Says "just a light snack." His light snack has more protein than my yearly intake. Also, why is he in EVERY movie?',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'May 2', type: 'text' },
        { id: '2', label: 'Daily Calories', value: '5,000 (before lunch)', type: 'text' },
        { id: '3', label: 'Signature Move', value: 'People\'s Elbow', type: 'text' },
        { id: '4', label: 'Fun Fact', value: 'Is actually made of muscles', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-10',
          title: 'Gym Session',
          body: 'He calls it "light cardio." I call it "torture." Did 500 pushups while giving me motivational speech. I did 5 pushups.',
          date: '2025-12-28T05:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-kanye',
      slug: 'kanye-west-demo',
      name: 'Kanye West',
      initials: 'KW',
      title: 'Genius (self-proclaimed)',
      company: 'YEEZY',
      location: 'Unknown (changes weekly)',
      email: 'ye@ye.ye',
      phone: '+1 (312) I-AM-GOD',
      tags: ['Acquaintance'],
      lastContact: '2025-12-26',
      personalNotes: 'Had a 3-hour conversation. He spoke for 2 hours 59 minutes. Topic was "Why Kanye is the Greatest Artist Ever." Evidence provided: "because I am." Hard to argue with that confidence. Now sells $200 hoodies with holes.',
      profileFields: [
        { id: '1', label: 'Birthday', value: 'June 8', type: 'text' },
        { id: '2', label: 'Favorite Person', value: 'Kanye West', type: 'text' },
        { id: '3', label: 'Humility Level', value: 'Error: Does not compute', type: 'text' },
        { id: '4', label: 'Fashion Sense', value: 'Post-apocalyptic chic', type: 'text' },
      ],
      interactionNotes: [
        {
          id: 'note-11',
          title: 'Listening Party',
          body: 'New album is just Kanye saying "Kanye" 47 times. He says it\'s "revolutionary." Critics are confused. So am I.',
          date: '2025-11-08T23:00:00Z',
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ].map((contact) => ({
    ...contact,
    daysAgo: contact.lastContact ? computeDaysAgo(contact.lastContact) : null,
  }));
};
